[2024-07-21T21:37:58.227+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-21T21:37:58.243+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: execute_databricks_workflow.run_databricks_workflow manual__2024-07-21T21:37:46.596317+00:00 [queued]>
[2024-07-21T21:37:58.248+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: execute_databricks_workflow.run_databricks_workflow manual__2024-07-21T21:37:46.596317+00:00 [queued]>
[2024-07-21T21:37:58.248+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-21T21:37:58.257+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_databricks_workflow> on 2024-07-21 21:37:46.596317+00:00
[2024-07-21T21:37:58.262+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=291) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-21T21:37:58.263+0000] {standard_task_runner.py:64} INFO - Started process 293 to run task
[2024-07-21T21:37:58.262+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'execute_databricks_workflow', 'run_databricks_workflow', 'manual__2024-07-21T21:37:46.596317+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/rotina_principal.py', '--cfg-path', '/tmp/tmp5kqf4x3x']
[2024-07-21T21:37:58.264+0000] {standard_task_runner.py:91} INFO - Job 19: Subtask run_databricks_workflow
[2024-07-21T21:37:58.293+0000] {task_command.py:426} INFO - Running <TaskInstance: execute_databricks_workflow.run_databricks_workflow manual__2024-07-21T21:37:46.596317+00:00 [running]> on host 383843094d1c
[2024-07-21T21:37:58.341+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='execute_databricks_workflow' AIRFLOW_CTX_TASK_ID='run_databricks_workflow' AIRFLOW_CTX_EXECUTION_DATE='2024-07-21T21:37:46.596317+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-21T21:37:46.596317+00:00'
[2024-07-21T21:37:58.342+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-21T21:37:58.893+0000] {logging_mixin.py:188} INFO - Erro ao executar job com job_id 968731268030929: {"error_code":401,"message":"Credential was not sent or was of an unsupported type for this API."}
[2024-07-21T21:37:58.894+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-21T21:37:58.894+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-21T21:37:58.901+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=execute_databricks_workflow, task_id=run_databricks_workflow, run_id=manual__2024-07-21T21:37:46.596317+00:00, execution_date=20240721T213746, start_date=20240721T213758, end_date=20240721T213758
[2024-07-21T21:37:58.917+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-21T21:37:58.929+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-21T21:37:58.931+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
