[2024-07-21T21:57:31.364+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-21T21:57:31.379+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: execute_databricks_workflow.run_databricks_workflow manual__2024-07-21T21:55:22.674718+00:00 [queued]>
[2024-07-21T21:57:31.384+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: execute_databricks_workflow.run_databricks_workflow manual__2024-07-21T21:55:22.674718+00:00 [queued]>
[2024-07-21T21:57:31.385+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-21T21:57:31.396+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_databricks_workflow> on 2024-07-21 21:55:22.674718+00:00
[2024-07-21T21:57:31.401+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=127) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-21T21:57:31.402+0000] {standard_task_runner.py:64} INFO - Started process 129 to run task
[2024-07-21T21:57:31.402+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'execute_databricks_workflow', 'run_databricks_workflow', 'manual__2024-07-21T21:55:22.674718+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/rotina_principal.py', '--cfg-path', '/tmp/tmpfwmcjc08']
[2024-07-21T21:57:31.404+0000] {standard_task_runner.py:91} INFO - Job 23: Subtask run_databricks_workflow
[2024-07-21T21:57:31.437+0000] {task_command.py:426} INFO - Running <TaskInstance: execute_databricks_workflow.run_databricks_workflow manual__2024-07-21T21:55:22.674718+00:00 [running]> on host 7d0a3577253e
[2024-07-21T21:57:31.497+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='execute_databricks_workflow' AIRFLOW_CTX_TASK_ID='run_databricks_workflow' AIRFLOW_CTX_EXECUTION_DATE='2024-07-21T21:55:22.674718+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-21T21:55:22.674718+00:00'
[2024-07-21T21:57:31.498+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-21T21:57:32.022+0000] {logging_mixin.py:188} INFO - Erro ao executar job com job_id 968731268030929: {"error_code":401,"message":"Credential was not sent or was of an unsupported type for this API."}
[2024-07-21T21:57:32.023+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-21T21:57:32.024+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-21T21:57:32.031+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=execute_databricks_workflow, task_id=run_databricks_workflow, run_id=manual__2024-07-21T21:55:22.674718+00:00, execution_date=20240721T215522, start_date=20240721T215731, end_date=20240721T215732
[2024-07-21T21:57:32.057+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-21T21:57:32.069+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-21T21:57:32.073+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
