[2024-07-23T20:01:58.831+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-23T20:01:58.948+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: processar_dados_brewery.transformar_dados_para_silver manual__2024-07-23T20:01:48.933569+00:00 [queued]>
[2024-07-23T20:01:58.954+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: processar_dados_brewery.transformar_dados_para_silver manual__2024-07-23T20:01:48.933569+00:00 [queued]>
[2024-07-23T20:01:58.955+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-23T20:01:58.963+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transformar_dados_para_silver> on 2024-07-23 20:01:48.933569+00:00
[2024-07-23T20:01:58.967+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=305) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-23T20:01:58.968+0000] {standard_task_runner.py:64} INFO - Started process 307 to run task
[2024-07-23T20:01:58.968+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'processar_dados_brewery', 'transformar_dados_para_silver', 'manual__2024-07-23T20:01:48.933569+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/rotina_principal.py', '--cfg-path', '/tmp/tmpat3lwkku']
[2024-07-23T20:01:58.970+0000] {standard_task_runner.py:91} INFO - Job 50: Subtask transformar_dados_para_silver
[2024-07-23T20:01:58.998+0000] {task_command.py:426} INFO - Running <TaskInstance: processar_dados_brewery.transformar_dados_para_silver manual__2024-07-23T20:01:48.933569+00:00 [running]> on host 84773d6c55d8
[2024-07-23T20:01:59.048+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='processar_dados_brewery' AIRFLOW_CTX_TASK_ID='transformar_dados_para_silver' AIRFLOW_CTX_EXECUTION_DATE='2024-07-23T20:01:48.933569+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-23T20:01:48.933569+00:00'
[2024-07-23T20:01:59.049+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-23T20:02:00.978+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-23T20:02:00.982+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/datalake_functions.py", line 142, in transformar_dados_para_silver
    df.to_parquet(silver_parquet_path, index=False, partition_cols=["estado_cidade"])
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 2970, in to_parquet
    return to_parquet(
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parquet.py", line 483, in to_parquet
    impl.write(
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parquet.py", line 216, in write
    self.api.parquet.write_to_dataset(
  File "/home/airflow/.local/lib/python3.12/site-packages/pyarrow/parquet/core.py", line 2138, in write_to_dataset
    ds.write_dataset(
  File "/home/airflow/.local/lib/python3.12/site-packages/pyarrow/dataset.py", line 1030, in write_dataset
    _filesystemdataset_write(
  File "pyarrow/_dataset.pyx", line 4010, in pyarrow._dataset._filesystemdataset_write
  File "pyarrow/error.pxi", line 91, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Fragment would be written into 3663 partitions. This exceeds the maximum of 1024
[2024-07-23T20:02:00.993+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=processar_dados_brewery, task_id=transformar_dados_para_silver, run_id=manual__2024-07-23T20:01:48.933569+00:00, execution_date=20240723T200148, start_date=20240723T200158, end_date=20240723T200200
[2024-07-23T20:02:01.002+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 50 for task transformar_dados_para_silver (Fragment would be written into 3663 partitions. This exceeds the maximum of 1024; 307)
[2024-07-23T20:02:01.026+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-23T20:02:01.042+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-23T20:02:01.044+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
