[2024-07-21T21:32:10.229+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-21T21:32:10.244+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: execute_databricks_workflow.run_databricks_workflow manual__2024-07-21T21:31:58.337316+00:00 [queued]>
[2024-07-21T21:32:10.249+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: execute_databricks_workflow.run_databricks_workflow manual__2024-07-21T21:31:58.337316+00:00 [queued]>
[2024-07-21T21:32:10.250+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-21T21:32:10.259+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_databricks_workflow> on 2024-07-21 21:31:58.337316+00:00
[2024-07-21T21:32:10.263+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=205) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-21T21:32:10.264+0000] {standard_task_runner.py:64} INFO - Started process 207 to run task
[2024-07-21T21:32:10.264+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'execute_databricks_workflow', 'run_databricks_workflow', 'manual__2024-07-21T21:31:58.337316+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/rotina_principal.py', '--cfg-path', '/tmp/tmphmklwm08']
[2024-07-21T21:32:10.265+0000] {standard_task_runner.py:91} INFO - Job 16: Subtask run_databricks_workflow
[2024-07-21T21:32:10.294+0000] {task_command.py:426} INFO - Running <TaskInstance: execute_databricks_workflow.run_databricks_workflow manual__2024-07-21T21:31:58.337316+00:00 [running]> on host 383843094d1c
[2024-07-21T21:32:10.343+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='execute_databricks_workflow' AIRFLOW_CTX_TASK_ID='run_databricks_workflow' AIRFLOW_CTX_EXECUTION_DATE='2024-07-21T21:31:58.337316+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-21T21:31:58.337316+00:00'
[2024-07-21T21:32:10.344+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-21T21:32:10.363+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-21T21:32:10.363+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/rotina_principal.py", line 93, in run_databricks_job
    response = requests.post(base_url, headers=headers, data=json.dumps(payload))
                                                             ^^^^
NameError: name 'json' is not defined. Did you forget to import 'json'
[2024-07-21T21:32:10.372+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=execute_databricks_workflow, task_id=run_databricks_workflow, run_id=manual__2024-07-21T21:31:58.337316+00:00, execution_date=20240721T213158, start_date=20240721T213210, end_date=20240721T213210
[2024-07-21T21:32:10.381+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 16 for task run_databricks_workflow (name 'json' is not defined; 207)
[2024-07-21T21:32:10.397+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-21T21:32:10.410+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-21T21:32:10.413+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
