[2024-07-21T21:34:52.910+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-21T21:34:52.926+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: execute_databricks_workflow.run_databricks_workflow manual__2024-07-21T21:31:58.337316+00:00 [queued]>
[2024-07-21T21:34:52.931+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: execute_databricks_workflow.run_databricks_workflow manual__2024-07-21T21:31:58.337316+00:00 [queued]>
[2024-07-21T21:34:52.931+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 3
[2024-07-21T21:34:52.940+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_databricks_workflow> on 2024-07-21 21:31:58.337316+00:00
[2024-07-21T21:34:52.944+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=243) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-21T21:34:52.945+0000] {standard_task_runner.py:64} INFO - Started process 245 to run task
[2024-07-21T21:34:52.945+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'execute_databricks_workflow', 'run_databricks_workflow', 'manual__2024-07-21T21:31:58.337316+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/rotina_principal.py', '--cfg-path', '/tmp/tmpoxf8thpx']
[2024-07-21T21:34:52.946+0000] {standard_task_runner.py:91} INFO - Job 17: Subtask run_databricks_workflow
[2024-07-21T21:34:52.977+0000] {task_command.py:426} INFO - Running <TaskInstance: execute_databricks_workflow.run_databricks_workflow manual__2024-07-21T21:31:58.337316+00:00 [running]> on host 383843094d1c
[2024-07-21T21:34:53.029+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='execute_databricks_workflow' AIRFLOW_CTX_TASK_ID='run_databricks_workflow' AIRFLOW_CTX_EXECUTION_DATE='2024-07-21T21:31:58.337316+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-21T21:31:58.337316+00:00'
[2024-07-21T21:34:53.030+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-21T21:34:53.050+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-21T21:34:53.051+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/rotina_principal.py", line 93, in run_databricks_job
    response = requests.post(base_url, headers=headers, data=json.dumps(payload))
                                                             ^^^^
NameError: name 'json' is not defined. Did you forget to import 'json'
[2024-07-21T21:34:53.059+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=execute_databricks_workflow, task_id=run_databricks_workflow, run_id=manual__2024-07-21T21:31:58.337316+00:00, execution_date=20240721T213158, start_date=20240721T213452, end_date=20240721T213453
[2024-07-21T21:34:53.068+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 17 for task run_databricks_workflow (name 'json' is not defined; 245)
[2024-07-21T21:34:53.078+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-21T21:34:53.090+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-21T21:34:53.091+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
