[2024-07-21T21:29:12.768+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-21T21:29:12.783+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: execute_databricks_workflow.run_databricks_workflow scheduled__2024-07-20T00:00:00+00:00 [queued]>
[2024-07-21T21:29:12.788+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: execute_databricks_workflow.run_databricks_workflow scheduled__2024-07-20T00:00:00+00:00 [queued]>
[2024-07-21T21:29:12.789+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 3
[2024-07-21T21:29:12.800+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_databricks_workflow> on 2024-07-20 00:00:00+00:00
[2024-07-21T21:29:12.804+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=164) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-21T21:29:12.805+0000] {standard_task_runner.py:64} INFO - Started process 166 to run task
[2024-07-21T21:29:12.805+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'execute_databricks_workflow', 'run_databricks_workflow', 'scheduled__2024-07-20T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/rotina_principal.py', '--cfg-path', '/tmp/tmpj3vp_gyh']
[2024-07-21T21:29:12.806+0000] {standard_task_runner.py:91} INFO - Job 14: Subtask run_databricks_workflow
[2024-07-21T21:29:12.840+0000] {task_command.py:426} INFO - Running <TaskInstance: execute_databricks_workflow.run_databricks_workflow scheduled__2024-07-20T00:00:00+00:00 [running]> on host 383843094d1c
[2024-07-21T21:29:12.895+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='execute_databricks_workflow' AIRFLOW_CTX_TASK_ID='run_databricks_workflow' AIRFLOW_CTX_EXECUTION_DATE='2024-07-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-20T00:00:00+00:00'
[2024-07-21T21:29:12.896+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-21T21:29:12.912+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-21T21:29:12.912+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/rotina_principal.py", line 80, in run_databricks_job
    token = Variable.get("databricks_token")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable databricks_token does not exist'
[2024-07-21T21:29:12.920+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=execute_databricks_workflow, task_id=run_databricks_workflow, run_id=scheduled__2024-07-20T00:00:00+00:00, execution_date=20240720T000000, start_date=20240721T212912, end_date=20240721T212912
[2024-07-21T21:29:12.928+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 14 for task run_databricks_workflow ('Variable databricks_token does not exist'; 166)
[2024-07-21T21:29:12.938+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-21T21:29:12.949+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-21T21:29:12.952+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
