[2024-07-23T19:42:31.544+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-23T19:42:31.676+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: processar_dados_brewery.buscar_e_salvar_dados_brewery manual__2024-07-23T19:42:29.442929+00:00 [queued]>
[2024-07-23T19:42:31.682+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: processar_dados_brewery.buscar_e_salvar_dados_brewery manual__2024-07-23T19:42:29.442929+00:00 [queued]>
[2024-07-23T19:42:31.682+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-23T19:42:31.691+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): buscar_e_salvar_dados_brewery> on 2024-07-23 19:42:29.442929+00:00
[2024-07-23T19:42:31.696+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=194) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-23T19:42:31.697+0000] {standard_task_runner.py:64} INFO - Started process 196 to run task
[2024-07-23T19:42:31.697+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'processar_dados_brewery', 'buscar_e_salvar_dados_brewery', 'manual__2024-07-23T19:42:29.442929+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/rotina_principal.py', '--cfg-path', '/tmp/tmps7o_ri8o']
[2024-07-23T19:42:31.698+0000] {standard_task_runner.py:91} INFO - Job 42: Subtask buscar_e_salvar_dados_brewery
[2024-07-23T19:42:31.730+0000] {task_command.py:426} INFO - Running <TaskInstance: processar_dados_brewery.buscar_e_salvar_dados_brewery manual__2024-07-23T19:42:29.442929+00:00 [running]> on host 4400ed802372
[2024-07-23T19:42:31.784+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='processar_dados_brewery' AIRFLOW_CTX_TASK_ID='buscar_e_salvar_dados_brewery' AIRFLOW_CTX_EXECUTION_DATE='2024-07-23T19:42:29.442929+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-23T19:42:29.442929+00:00'
[2024-07-23T19:42:31.785+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-23T19:42:31.799+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-23T19:42:31.800+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/datalake_functions.py", line 11, in buscar_e_salvar_dados_brewery
    os.makedirs(landing_zone_path, exist_ok=True)
  File "<frozen os>", line 225, in makedirs
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/datalake/landing_zone'
[2024-07-23T19:42:31.808+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=processar_dados_brewery, task_id=buscar_e_salvar_dados_brewery, run_id=manual__2024-07-23T19:42:29.442929+00:00, execution_date=20240723T194229, start_date=20240723T194231, end_date=20240723T194231
[2024-07-23T19:42:31.816+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 42 for task buscar_e_salvar_dados_brewery ([Errno 2] No such file or directory: '/opt/airflow/datalake/landing_zone'; 196)
[2024-07-23T19:42:31.831+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-23T19:42:31.848+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-23T19:42:31.851+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
